"""Status constants for leave management system"""

# Leave request statuses
LEAVE_STATUS_PENDING = "PENDING"
LEAVE_STATUS_APPROVED = "APPROVED"
LEAVE_STATUS_REJECTED = "REJECTED"

LEAVE_STATUSES = [
    LEAVE_STATUS_PENDING,
    LEAVE_STATUS_APPROVED,
    LEAVE_STATUS_REJECTED
]

# Leave duration types
LEAVE_DURATION_FULL_DAY = "FULL_DAY"
LEAVE_DURATION_FIRST_HALF = "FIRST_HALF"
LEAVE_DURATION_SECOND_HALF = "SECOND_HALF"

LEAVE_DURATIONS = [
    LEAVE_DURATION_FULL_DAY,
    LEAVE_DURATION_FIRST_HALF,
    LEAVE_DURATION_SECOND_HALF
]
