"""Initial schema

Revision ID: a6617094fbf7
Revises: 
Create Date: 2026-03-04 15:14:41.025999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6617094fbf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index('idx_holidays_date_location', ['date', 'location'], unique=False)
        batch_op.create_index('idx_holidays_deleted_at', ['deleted_at'], unique=False)

    op.create_table('leave_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('yearly_quota', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.create_index('idx_leave_types_active', ['is_active'], unique=False)
        batch_op.create_index('idx_leave_types_deleted_at', ['deleted_at'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index('idx_permissions_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('idx_permissions_name', ['name'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('idx_users_email', ['email'], unique=False)

    op.create_table('employee_holidays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('holiday_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['holiday_id'], ['holidays.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'holiday_id', name='uq_employee_holiday')
    )
    with op.batch_alter_table('employee_holidays', schema=None) as batch_op:
        batch_op.create_index('idx_employee_holidays_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('idx_employee_holidays_user', ['user_id'], unique=False)

    op.create_table('leave_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_quota', sa.Integer(), nullable=False),
    sa.Column('used_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('total_quota >= 0', name='check_total_quota'),
    sa.CheckConstraint('used_days >= 0', name='check_used_days'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'leave_type_id', 'year', name='uq_user_leavetype_year')
    )
    with op.batch_alter_table('leave_ledger', schema=None) as batch_op:
        batch_op.create_index('idx_leave_ledger_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('idx_leave_ledger_user_year', ['user_id', 'year'], unique=False)

    op.create_table('leave_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('cancellation_requested', sa.Boolean(), nullable=False),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('cancellation_requested_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('start_date <= end_date', name='check_leave_dates'),
    sa.CheckConstraint('total_days > 0', name='check_total_days'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index('idx_leave_requests_applied_at', ['applied_at'], unique=False)
        batch_op.create_index('idx_leave_requests_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('idx_leave_requests_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('idx_leave_requests_user_deleted', ['user_id', 'deleted_at'], unique=False)
        batch_op.create_index('idx_leave_requests_user_status', ['user_id', 'status'], unique=False)

    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index('idx_role_permissions_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('idx_role_permissions_role', ['role_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index('idx_user_roles_deleted_at', ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index('idx_user_roles_deleted_at')

    op.drop_table('user_roles')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_role_permissions_role')
        batch_op.drop_index('idx_role_permissions_deleted_at')

    op.drop_table('role_permissions')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_leave_requests_user_status')
        batch_op.drop_index('idx_leave_requests_user_deleted')
        batch_op.drop_index('idx_leave_requests_deleted_at')
        batch_op.drop_index('idx_leave_requests_dates')
        batch_op.drop_index('idx_leave_requests_applied_at')

    op.drop_table('leave_requests')
    with op.batch_alter_table('leave_ledger', schema=None) as batch_op:
        batch_op.drop_index('idx_leave_ledger_user_year')
        batch_op.drop_index('idx_leave_ledger_deleted_at')

    op.drop_table('leave_ledger')
    with op.batch_alter_table('employee_holidays', schema=None) as batch_op:
        batch_op.drop_index('idx_employee_holidays_user')
        batch_op.drop_index('idx_employee_holidays_deleted_at')

    op.drop_table('employee_holidays')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_email')
        batch_op.drop_index('idx_users_deleted_at')

    op.drop_table('users')
    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_permissions_name')
        batch_op.drop_index('idx_permissions_deleted_at')

    op.drop_table('permissions')
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.drop_index('idx_leave_types_deleted_at')
        batch_op.drop_index('idx_leave_types_active')

    op.drop_table('leave_types')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index('idx_holidays_deleted_at')
        batch_op.drop_index('idx_holidays_date_location')

    op.drop_table('holidays')
    # ### end Alembic commands ###
